version: 0.2

phases:
    install:
        commands:
            - echo Executing Install Phase
            
    pre_build:
        commands:
            - aws --version
            - echo Executing Pre Build Phase

    build:
        commands:
            - echo Executing Build Phase
            - echo Build started on `date`

    post_build:
        commands:
            - echo Executing Post Build Phase
            - echo Build completed on `date`

artifacts:
    files:
        - appspec.yml
        - "**/*"
