version: 0.2

phases:
    install:
        commands:
            - echo Executing Install Phase
            
    pre_build:
        commands:
            - echo Executing Pre Build Phase
            - aws --version
            - echo Logging in..
            - docker login -u=waqaskayani -p=123456789

    build:
        commands:
            - echo Executing Build Phase
            - echo Build started on `date`
            - "docker build --tag waqaskayani/todolist:app ."
            - "docker tag waqaskayani/todolist:app waqaskayani/todolist:app"
            - docker-compose pull && docker-compose up -d
            - echo Running unittest..
            - python -m unittest discover tests

    post_build:
        commands:
            - echo Executing Post Build Phase
            - "docker push waqaskayani/todolist:app"
            - echo Build completed on `date`

artifacts:
    files:
        - appspec.yml
        - "**/*"
